### ISSUE TITLE
Tracking issue: WCAG compliance

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#254]
This is a super-ticket for tracking the various WCAG compliance issues that have been raised

- [ ] #242 content in landmarks
- [ ] #243 ARIA role for dialogue
- [ ] #244 colour contrast
- [ ] #245 form element labels
- [ ] #246 h1 heading
- [ ] #249 keyboard focus
- [ ] #250 tabbing
- [ ] #252 keyboard focus for type-of-property
- [ ] #253 keyboard focus graph tabs

**Comment by ijdickinson** [comment]
All known issues have been addressed
